### ISSUE TITLE
Solution  UVa-online-judge/501.cpp is wrong

### ISSUE THREAD

**Issue by canhnht** [ksaveljev/UVa-online-judge#2]
I tested the solution [501 UVA](https://github.com/ksaveljev/UVa-online-judge/blob/master/501.cpp) with this testcase:
```
1

3 5
10 20 30
3 3 3 3 3
```

It gave **Segmentation fault (core dumped)**

**Comment by ksaveljev** [comment]
Hey, it's been quite some time since the solution has been added but looking at the problem statement it does say that N is less or equal than M, and in your test case M = 3 and N = 5... so it is not a valid input?

**Comment by canhnht** [comment]
Oh, my bad. Sorry, it's invalid input. :)
